

POST http://localhost:3000/auth/register HTTP/1.1
content-type: application/json

{
    "name": "Jonh Doe",
    "email": "jonhdoe@gmail.com",
    "password": "jonhdoe@Password"
}

###

POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "jonhdoe@gmail.com",
    "password": "jonhdoe@Password"
}