@token = Bearer ...

POST http://localhost:3000/categories HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "name": "mobile",
    "description": "all kinds of laptop."
}

###

GET http://localhost:3000/categories HTTP/1.1
content-type: application/json
Authorization: {{token}}