POST http://localhost:3000/categories HTTP/1.1
content-type: application/json

{
    "name": "laptop",
    "description": "all kinds of laptop."
}

###

GET http://localhost:3000/categories HTTP/1.1
content-type: application/json
