POST http://localhost:3000/orders HTTP/1.1
content-type: application/json

{
    "userId": 2,
    "status": "pending",
    "items": [
        {
            "productId": 1,
            "qty": 8
        },
        {
            "productId": 2,
            "qty": 3
        },
        {
            "productId": 3,
            "qty": 15
        }
    ]
}

###

GET http://localhost:3000/orders HTTP/1.1
content-type: application/json
