@token = Bearer ...

POST http://localhost:3000/orders HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "userId": 2,
    "status": "pending",
    "items": [
        {
            "productId": 2,
            "qty": 2
        },
        {
            "productId": 1,
            "qty": 4
        }
    ]
}

###

GET http://localhost:3000/orders HTTP/1.1
content-type: application/json
Authorization: {{token}}


###

PATCH  http://localhost:3000/orders/cancelled HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "id": 17
}