@token = Bearer ...

POST http://localhost:3000/payments HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "orderId": 20,
    "status": "pending",
    "amount": 2200
}

###

GET http://localhost:3000/payments?limit=2&offset=0 HTTP/1.1
content-type: application/json
Authorization: {{token}}


###

PATCH  http://localhost:3000/payments/cancelled HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "id": 6
}

###

PATCH  http://localhost:3000/payments/paid HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "id": 7
}