POST http://localhost:3000/products HTTP/1.1
content-type: application/json

{
    "name": "iphone SE",
    "description": "Apple iphone product",
    "price": 599,
    "categoryId": 1,
    "qty": 10
}

###

GET http://localhost:3000/products HTTP/1.1
content-type: application/json


###

PATCH http://localhost:3000/products/1 HTTP/1.1
content-type: application/json

{
    "qty": 16
}
