@token = Bearer ...

POST http://localhost:3000/products HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "name": "iphone SE",
    "description": "Apple iphone product",
    "price": 599,
    "categoryId": 1,
    "qty": 10
}

###

GET http://localhost:3000/products?limit=2&offset=0 HTTP/1.1
content-type: application/json
Authorization: {{token}}


###

PATCH http://localhost:3000/products/1 HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "qty": 16
}
