@token = Bearer ...


###

GET http://localhost:3000/reports/export/sales HTTP/1.1
content-type: application/json
Authorization: {{token}}

###

GET http://localhost:3000/reports/sales?limit=2&offset=0 HTTP/1.1
content-type: application/json
Authorization: {{token}}